trigge compile-time error if Which() is called with 1 argument
The g++ compiler error is very descriptive in this case:

error: no matching function for call to Which(bool)
note:  candidate expects 2 arguments, 1 provided